module.exports = {
  nesting: [
    'Copulation/Mating',
    'Nest Construction',
    'Incubation',
    'Hatchling',
    'Brooding',
    'Other (Specify in Notes)',
  ],
  behavior: [
    'Roosting',
    'Foraging',
    'Sitting',
    'Courting',
    'Fishing',
    'Flying',
    'Flushing',
    'Distraction Behavior',
    'Feeding',
    'Other (Specify in Notes)',
  ],
  habitat: [
    'Sandy beach',
    'Dunes',
    'Vegetation-Native',
    'Vegetation-Non-Native',
    'Groomed',
    'Stone/cobble',
    'Rocky/outcroppings',
  ],
};
